#generated by gps 230620

import rclpy
from rclpy.node import Node
from nav_msgs.msg import Odometry
import matplotlib.pyplot as plt

class OdomPlot(Node):

    def __init__(self):
        super().__init__('odom_plot')
        self.subscription = self.create_subscription(
            Odometry,
            'erp_odom',
            self.listener_callback,
            10)
        self.subscription
        self.x_data = []
        self.y_data = []

    def listener_callback(self, msg):
        self.x_data.append(msg.pose.pose.position.x)
        self.y_data.append(msg.pose.pose.position.y)

        plt.cla()
        plt.plot(self.x_data, self.y_data)
        plt.pause(0.01)

def main(args=None):
    rclpy.init(args=args)

    subscriber = OdomPlot()

    plt.ion()
    plt.show()

    rclpy.spin(subscriber)

    subscriber.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
